DeleteStreetMarketing - INFO - check street marketing exists
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [249]
uvicorn.error - INFO - Started server process [255]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [255]
uvicorn.error - INFO - Started server process [257]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [257]
uvicorn.error - INFO - Started server process [259]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
DeleteStreetMarketing - INFO - check street marketing exists
DeleteStreetMarketing - INFO - check street marketing exists
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [259]
uvicorn.error - INFO - Started server process [266]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
DeleteStreetMarketing - INFO - check street marketing exists
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [266]
uvicorn.error - INFO - Started server process [270]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [270]
uvicorn.error - INFO - Started server process [272]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [272]
uvicorn.error - INFO - Started server process [274]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
DeleteStreetMarketing - INFO - check street marketing exists
DeleteStreetMarketing - INFO - delete street marketing
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/src/./main.py", line 65, in delete
    DeleteStreetMarketing(id).execute()
  File "/src/./app/use_cases/delete_street_marketing.py", line 14, in execute
    self.delete()
  File "/src/./app/use_cases/delete_street_marketing.py", line 27, in delete
    self.repository.delete({'_id', self.street_marketing.id })
  File "/src/./app/repositories/base_repository.py", line 19, in delete
    return self.collection.delete_one(query)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1248, in delete_one
    self._delete_retryable(
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1206, in _delete_retryable
    return self.__database.client._retryable_write(
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1552, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1438, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1470, in _retry_internal
    return func(session, sock_info, retryable)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1200, in _delete
    return self._delete(
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1143, in _delete
    common.validate_is_mapping("filter", criteria)
  File "/usr/local/lib/python3.8/site-packages/pymongo/common.py", line 495, in validate_is_mapping
    raise TypeError("%s must be an instance of dict, bson.son.SON, or "
TypeError: filter must be an instance of dict, bson.son.SON, or any other type that inherits from collections.Mapping
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [274]
uvicorn.error - INFO - Started server process [278]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
DeleteStreetMarketing - INFO - check street marketing exists
DeleteStreetMarketing - INFO - delete street marketing
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/src/./main.py", line 65, in delete
    DeleteStreetMarketing(id).execute()
  File "/src/./app/use_cases/delete_street_marketing.py", line 14, in execute
    self.delete()
  File "/src/./app/use_cases/delete_street_marketing.py", line 27, in delete
    self.repository.delete({'_id', self.street_marketing.id })
  File "/src/./app/repositories/base_repository.py", line 19, in delete
    return self.collection.delete_one(query)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1248, in delete_one
    self._delete_retryable(
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1206, in _delete_retryable
    return self.__database.client._retryable_write(
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1552, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1438, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1470, in _retry_internal
    return func(session, sock_info, retryable)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1200, in _delete
    return self._delete(
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1143, in _delete
    common.validate_is_mapping("filter", criteria)
  File "/usr/local/lib/python3.8/site-packages/pymongo/common.py", line 495, in validate_is_mapping
    raise TypeError("%s must be an instance of dict, bson.son.SON, or "
TypeError: filter must be an instance of dict, bson.son.SON, or any other type that inherits from collections.Mapping
DeleteStreetMarketing - INFO - check street marketing exists
DeleteStreetMarketing - INFO - delete street marketing
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/src/./main.py", line 65, in delete
    DeleteStreetMarketing(id).execute()
  File "/src/./app/use_cases/delete_street_marketing.py", line 14, in execute
    self.delete()
  File "/src/./app/use_cases/delete_street_marketing.py", line 27, in delete
    self.repository.delete({'_id', self.street_marketing.id })
  File "/src/./app/repositories/base_repository.py", line 19, in delete
    return self.collection.delete_one(query)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1248, in delete_one
    self._delete_retryable(
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1206, in _delete_retryable
    return self.__database.client._retryable_write(
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1552, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1438, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1470, in _retry_internal
    return func(session, sock_info, retryable)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1200, in _delete
    return self._delete(
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1143, in _delete
    common.validate_is_mapping("filter", criteria)
  File "/usr/local/lib/python3.8/site-packages/pymongo/common.py", line 495, in validate_is_mapping
    raise TypeError("%s must be an instance of dict, bson.son.SON, or "
TypeError: filter must be an instance of dict, bson.son.SON, or any other type that inherits from collections.Mapping
DeleteStreetMarketing - INFO - check street marketing exists
DeleteStreetMarketing - INFO - delete street marketing
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/src/./main.py", line 65, in delete
    DeleteStreetMarketing(id).execute()
  File "/src/./app/use_cases/delete_street_marketing.py", line 14, in execute
    self.delete()
  File "/src/./app/use_cases/delete_street_marketing.py", line 27, in delete
    self.repository.delete({'_id', self.street_marketing.id })
  File "/src/./app/repositories/base_repository.py", line 19, in delete
    return self.collection.delete_one(query)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1248, in delete_one
    self._delete_retryable(
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1206, in _delete_retryable
    return self.__database.client._retryable_write(
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1552, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1438, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1470, in _retry_internal
    return func(session, sock_info, retryable)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1200, in _delete
    return self._delete(
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1143, in _delete
    common.validate_is_mapping("filter", criteria)
  File "/usr/local/lib/python3.8/site-packages/pymongo/common.py", line 495, in validate_is_mapping
    raise TypeError("%s must be an instance of dict, bson.son.SON, or "
TypeError: filter must be an instance of dict, bson.son.SON, or any other type that inherits from collections.Mapping
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [278]
uvicorn.error - INFO - Started server process [287]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
DeleteStreetMarketing - INFO - check street marketing exists
DeleteStreetMarketing - INFO - delete street marketing
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/src/./main.py", line 65, in delete
    DeleteStreetMarketing(id).execute()
  File "/src/./app/use_cases/delete_street_marketing.py", line 14, in execute
    self.delete()
  File "/src/./app/use_cases/delete_street_marketing.py", line 27, in delete
    self.repository.delete_one({'_id', self.street_marketing.id })
AttributeError: 'StreetMarketRepository' object has no attribute 'delete_one'
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [287]
uvicorn.error - INFO - Started server process [291]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
DeleteStreetMarketing - INFO - check street marketing exists
DeleteStreetMarketing - INFO - delete street marketing
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/src/./main.py", line 65, in delete
    DeleteStreetMarketing(id).execute()
  File "/src/./app/use_cases/delete_street_marketing.py", line 14, in execute
    self.delete()
  File "/src/./app/use_cases/delete_street_marketing.py", line 27, in delete
    self.repository.delete_one({'_id', self.street_marketing.id })
  File "/src/./app/repositories/base_repository.py", line 19, in delete_one
    return self.collection.delete_one(query)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1248, in delete_one
    self._delete_retryable(
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1206, in _delete_retryable
    return self.__database.client._retryable_write(
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1552, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1438, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1470, in _retry_internal
    return func(session, sock_info, retryable)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1200, in _delete
    return self._delete(
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1143, in _delete
    common.validate_is_mapping("filter", criteria)
  File "/usr/local/lib/python3.8/site-packages/pymongo/common.py", line 495, in validate_is_mapping
    raise TypeError("%s must be an instance of dict, bson.son.SON, or "
TypeError: filter must be an instance of dict, bson.son.SON, or any other type that inherits from collections.Mapping
DeleteStreetMarketing - INFO - check street marketing exists
DeleteStreetMarketing - INFO - delete street marketing
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/src/./main.py", line 65, in delete
    DeleteStreetMarketing(id).execute()
  File "/src/./app/use_cases/delete_street_marketing.py", line 14, in execute
    self.delete()
  File "/src/./app/use_cases/delete_street_marketing.py", line 27, in delete
    self.repository.delete_one({'_id', self.street_marketing.id })
  File "/src/./app/repositories/base_repository.py", line 19, in delete_one
    return self.collection.delete_one(query)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1248, in delete_one
    self._delete_retryable(
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1206, in _delete_retryable
    return self.__database.client._retryable_write(
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1552, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1438, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1470, in _retry_internal
    return func(session, sock_info, retryable)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1200, in _delete
    return self._delete(
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1143, in _delete
    common.validate_is_mapping("filter", criteria)
  File "/usr/local/lib/python3.8/site-packages/pymongo/common.py", line 495, in validate_is_mapping
    raise TypeError("%s must be an instance of dict, bson.son.SON, or "
TypeError: filter must be an instance of dict, bson.son.SON, or any other type that inherits from collections.Mapping
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [291]
uvicorn.error - INFO - Started server process [297]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
DeleteStreetMarketing - INFO - check street marketing exists
DeleteStreetMarketing - INFO - delete street marketing
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/src/./main.py", line 65, in delete
    DeleteStreetMarketing(id).execute()
  File "/src/./app/use_cases/delete_street_marketing.py", line 14, in execute
    self.delete()
  File "/src/./app/use_cases/delete_street_marketing.py", line 27, in delete
    self.repository.delete_one({'codigo', self.id })
  File "/src/./app/repositories/base_repository.py", line 19, in delete_one
    return self.collection.delete_one(query)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1248, in delete_one
    self._delete_retryable(
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1206, in _delete_retryable
    return self.__database.client._retryable_write(
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1552, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1438, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1470, in _retry_internal
    return func(session, sock_info, retryable)
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1200, in _delete
    return self._delete(
  File "/usr/local/lib/python3.8/site-packages/pymongo/collection.py", line 1143, in _delete
    common.validate_is_mapping("filter", criteria)
  File "/usr/local/lib/python3.8/site-packages/pymongo/common.py", line 495, in validate_is_mapping
    raise TypeError("%s must be an instance of dict, bson.son.SON, or "
TypeError: filter must be an instance of dict, bson.son.SON, or any other type that inherits from collections.Mapping
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [297]
uvicorn.error - INFO - Started server process [301]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [301]
uvicorn.error - INFO - Started server process [303]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [303]
uvicorn.error - INFO - Started server process [306]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
DeleteStreetMarketing - INFO - check street marketing exists
DeleteStreetMarketing - INFO - delete street marketing
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [306]
uvicorn.error - INFO - Started server process [310]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [310]
uvicorn.error - INFO - Started server process [312]
uvicorn.error - INFO - Waiting for application startup.
uvicorn.error - INFO - Application startup complete.
DeleteStreetMarketing - INFO - check street marketing exists
DeleteStreetMarketing - INFO - check street marketing exists
DeleteStreetMarketing - INFO - delete street marketing
